### ISSUE TITLE
Reporting ABR_occlusion_query unsupported when it looks like it is

### ISSUE THREAD

**Issue by Olliebrown** [apitrace/apitrace#358]
I am unable to profile gpu pixel draws because it reports "GL_ARB_occlusion_query extension is not supported".  However, glewinfo reports that it is (and the Wildfire database agrees with this: http://feedback.wildfiregames.com/report/opengl/device/GeForce%20GT%20750M)

This is on a mid 2014 Macbook Pro running OSX 10.9.5 w/ a GeForce GT 750M.  I use gfxCardStatus to ensure only the dedicated Nvidia GPU is enabled before running.

Here's is some output to show the situation:
```
c-12293:ReflectanceAcquisition berriers$ /Users/berriers/Programming/apitrace/apitrace/build/glretrace --pgpu --pcpu --ppd --pmem java.trace 
# call no gpu_start gpu_dura cpu_start cpu_dura vsize_start vsize_dura rss_start rss_dura pixels program name
Error: Cannot run profile, GL_ARB_occlusion_query extension is not supported.
c-12293:ReflectanceAcquisition berriers$ glewinfo | grep occlusion
GL_AMD_occlusion_query_event:                                  MISSING 
GL_ARB_occlusion_query:                                        OK 
GL_ARB_occlusion_query2:                                       MISSING 
GL_HP_occlusion_test:                                          MISSING 
GL_NV_occlusion_query:                                         MISSING 
```

**Comment by Olliebrown** [comment]
I went into glprofile.cpp and had it print out all the extensions it was seeing and curiously it shows GL_ARB_occlusion_query2 as supported but NOT GL_ARB_occlusion_query (which explains the error).  I'm not sure why GLEW gives such a different list of supported extensions.  I'm guessing it has something to do with being in CORE profile instead of the LEGACY one.

Anyways, reading about GL_ARB_occlusion_query2 it seems it is 100% backwards compatible to GL_ARB_occlusion_query (begs the question why the driver doesn't simply report both as supported) but to get around this I made the following modification in glretrace_main.cpp around line 372:

```C++
supportsOcclusion   = currentContext->hasExtension("GL_ARB_occlusion_query");
supportsOcclusion   = currentContext->hasExtension("GL_ARB_occlusion_query2") || supportsOcclusion;
```

Now when I run it with pixel count profiling enabled it works and I get reasonable looking pixel counts.

**Comment by jrfonseca** [comment]
I understand the problem. I'll push a fix very shortly.

**Comment by jrfonseca** [comment]
Fixed now.

Apple is a bit unique since it doesn't list non-core extensions on their 3.2+ core profiles.  Which is a perfectly valid thing to do, but just needs extra attention for app developers.

Thanks for reporting the issue.

**Comment by Olliebrown** [comment]
Thank you for the explanation and quick response!

**Comment by iMineLink** [comment]
I have a Nvidia GTX 770 (stated to support GL_ARB_occlusion_query and GL_ARB_occlusion_query2) with 353.30 drivers on Windows 7 64 bit, and the bug is still present regardless of your fix. I don't actually have the build tools to test some modifications, sorry!

**Comment by jrfonseca** [comment]
@iMineLink, the issue @Olliebrown reported here is quite specific to Mac OS. Whatever's happening on Windows NVIDIA must be something different.

Can you confirm that, you're getting the "GL_ARB_occlusion_query extension is not supported" message when you do `glretrace --pgpu --pcpu your-application.trace`, and that you're using the latest binaries from http://people.freedesktop.org/~jrfonseca/apitrace/ ?

**Comment by iMineLink** [comment]
When using "--pgpu --pcpu" as parameters, no error is given, but:
1) "--pgpu --pcpu --ppd": gives the "GL_ARB_occlusion_query extension is not supported" message
2) "--pgpu --pcpu --ppd --pmem": gives the "GL_ARB_occlusion_query extension is not supported" message
3) "--pgpu --pcpu --pmem": works.

So I think the problem is the "--ppd" (pixel drawn per call, i think) parameter that's causing the issue.

Using "--pmem" I got some random crashes when using the GUI, but now I'm profiling a trace without problems, so who knows.

**Comment by jrfonseca** [comment]
Currently, ARB_occlusion_query is detected as long as OpenGL version is desktop (not ES) version 1.5 or later.

@iMineLink, please obtain a trace of glretrace itself, ie:

    apitrace trace -a gl -o glretrace.trace glretrace --pgpu --pcpu --ppd your-application.trace

and provide this trace somehow (dropbox, google drive, etc).  It should be a small trace, as glretrace will fail from the start.  But it should contain all info necessary to understand why glretrace thinks that `GL_ARB_occlusion_query` is missing.

**Comment by iMineLink** [comment]
https://www.dropbox.com/s/c74yhp5bqcdjmqk/glretrace.trace?dl=0

Here's the trace requested.

**Comment by jrfonseca** [comment]
@iMineLink Thanks.  I understood what was going on.  This should be now fixed with 6d7ddcc5594d334f926aa2e0546ab5b57b9a1e3c

**Comment by iMineLink** [comment]
It now works!
But, what is "--pmem" supposed to do? I get no valuable output running the program with that parameter.

**Comment by jrfonseca** [comment]
> It now works!

Great.

> But, what is "--pmem" supposed to do? I get no valuable output running the program with that parameter.

Memory (CPU, not GPU) usage profiling.  It's only implemented on Linux.  Adding a warning that's not supported on other OSes would be helpful.  But it's probably just as easy to implement memory profiling on other OSes too.

I never cared much, as to me GPU memory profiling would be more useful. However it's not implemented on any OS.  (It would require vendor specific extensions.)

**Comment by iMineLink** [comment]
Thanks for the info, though it would be not that useful to profile CPU mem (it's not source of big issues nowadays), it would be rather useful to profile GPU mem, as you say, just as nVidia is doing with her https://developer.nvidia.com/linux-graphics-debugger , but with the interoperabilty of apitrace.
