### ISSUE TITLE
apitrace trace -a egl tries to emit glX calls on Wayland, when using libGL

### ISSUE THREAD

**Issue by linkmauve** [apitrace/apitrace#380]
Which results in this error after the first GL call:
`glXGetCurrentContext() not found in libGL.so.1: /usr/bin/../lib/apitrace/wrappers/egltrace.so: undefined symbol: glXGetCurrentContext`

This doesn’t happen on a GLES context using libGLESv2 instead of libGL.

**Comment by jrfonseca** [comment]
I don't have Wayland. Could you try obtaining a stack back trace, following the instructions on https://github.com/apitrace/apitrace/blob/master/docs/BUGS.markdown#linux

**Comment by linkmauve** [comment]
This one doesn’t crash, apitrace handles the missing symbol gracefully before exiting with a status 1:
```
apitrace: unloaded from /tmp/a.out
```

**Comment by jrfonseca** [comment]
> This one doesn’t crash, apitrace handles the missing symbol gracefully before exiting with a status 1

Please try putting a breakpoint  on `abort` or `_exit`.  Seeing the backtrace of when this happens would really help me understand what's going on.

**Comment by linkmauve** [comment]
It seems this one is entirely due to libepoxy, which will try to use glX when running in apitrace for some reason:
```
Breakpoint 1, 0x00007ffff6faccd0 in _exit () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007ffff6faccd0 in _exit () from /usr/lib/libc.so.6
#1  0x00007ffff6f29f3b in __run_exit_handlers () from /usr/lib/libc.so.6
#2  0x00007ffff6f29fd5 in exit () from /usr/lib/libc.so.6
#3  0x00007ffff72f051a in do_dlsym (handle=<optimized out>, lib_name=0x7ffff7344b20 "libGL.so.1", name=0x7ffff7362b77 <entrypoint_strings+1143> "glXGetCurrentContext", exit_on_fail=<optimized out>)
    at dispatch_common.c:262
#4  0x00007ffff73413c6 in glx_provider_resolver (entrypoints=0x7fffffffda2c, providers=0x7fffffffda30, name=0x7ffff7362b77 <entrypoint_strings+1143> "glXGetCurrentContext") at glx_generated_dispatch.c:562
#5  glx_single_resolver (provider=provider@entry=GLX_10, entrypoint_offset=entrypoint_offset@entry=1143) at glx_generated_dispatch.c:590
#6  0x00007ffff7342c26 in epoxy_glXGetCurrentContext_resolver () at glx_generated_dispatch.c:903
#7  epoxy_glXGetCurrentContext_global_rewrite_ptr () at glx_generated_dispatch.c:1425
#8  0x00007ffff72f0553 in epoxy_current_context_is_glx () at dispatch_common.c:412
#9  0x00007ffff72f060d in epoxy_is_desktop_gl () at dispatch_common.c:282
#10 0x00007ffff72f6635 in gl_provider_resolver (name=0x7ffff7354ad8 <entrypoint_strings+16120> "glGenTextures", providers=0x7ffff734ef78 <providers>, entrypoints=0x7ffff734ef72 <entrypoints>)
    at gl_generated_dispatch.c:7319
#11 0x00007ffff73240b9 in epoxy_glGenTextures_resolver () at gl_generated_dispatch.c:18408
#12 epoxy_glGenTextures_global_rewrite_ptr (n=1, textures=0x7fffffffdb54) at gl_generated_dispatch.c:46117
#13 0x00000000004009c0 in main ()
```

I have opened an issue on their bugtracker, here: https://github.com/anholt/libepoxy/issues/68

**Comment by jrfonseca** [comment]
The problem is explained in https://github.com/anholt/libepoxy/issues/68#issuecomment-136723603 .

This could be fixed apitrace, if `egltrace.so` is modified to not intercept `dlopen`, but only `dlsym`.  However, that would be a far reaching change, with many unpredicatble side-effects, so I rather not doit. Specially given that small `libepoxy` fix would avoid this too.

I also hope one day to unify `egltrace.so` and `glxtrace.so`, which would make this problem go away too.

**Comment by jrfonseca** [comment]
I don't plan to take any further action on this issue, so closing.

**Comment by linkmauve** [comment]
Fyi, this issue is now fixed in libepoxy by this commit: https://github.com/anholt/libepoxy/commit/dbfa4b209c0712b67dfeb8366c2ebe8503063b52

**Comment by valpackett** [comment]
Currently, it seems to require setting `TRACE_LIBGL=` (empty string), as found in https://github.com/anholt/libepoxy/issues/283 — otherwise I still get the error
