### ISSUE TITLE
capture/replay broken for indirect draws

### ISSUE THREAD

**Issue by zmike** [apitrace/apitrace#903]
From https://github.com/apitrace/apitrace/issues/874#issuecomment-1766552710

@jrfonseca I tried https://github.com/zmike/apitrace/commit/5e9428d62a464c68dd4f71ba1b621695c4fc6713 to add the same sort of handling, but I guess I misunderstood what you were suggesting since it doesn't seem to have any effect and replay still crashes.

**Comment by jrfonseca** [comment]
You did pretty much what I had in mind with https://github.com/apitrace/apitrace/issues/874#issuecomment-1766552710

Maybe there's a non obvious bug here or the crash mechanism is different.

Can you share the trace or dump of last couple dozen of calls ?

**Comment by zmike** [comment]
trace [here](https://mega.nz/file/9MFRRKaC#UqWPPEFKR7DdjxU-NoRsfYZ7oIbHZBnniFrUUoMD7xQ)

**Comment by jrfonseca** [comment]
My hunch was actually right -- the issue is indeed the polymorphism of the `indirect` parameter:

```
...
3975364 @0 glMultiDrawElementsIndirect(mode = GL_TRIANGLES, type = GL_UNSIGNED_INT, indirect = 0x55560c2ff470, drawcount = 1, stride = 20)
warning: passing high address 0x55560c2ff470 as uintptr_t
apitrace: warning: caught signal 11
```

`indirect` should have been a blob here, instead of an offset pointer.

Was this trace recorded with your patch?  Because I completely forgot to mention(!): that change https://github.com/zmike/apitrace/commit/5e9428d62a464c68dd4f71ba1b621695c4fc6713 will not change the glretrace's behavior, but rather the tracing.

**Comment by jrfonseca** [comment]
BTW, this is a very odd/useless thing for an OpenGL app to do: do an indirect draw, with the indirect parameters in CPU memory...! :facepalm: 

It was to avoid weird state combinations with legacy like that the _core profiles_ were created.  But in the end everybody yielded: compatibility profiles are widely expected and supported.  The only way to avoid legacy is to avoid OpenGL altogether and use something like Vulkan.

**Comment by zmike** [comment]
Yeah, I'm just trying to fix (possible) driver bugs that people report :face_with_head_bandage: 

I don't recall if this specific trace was recorded with or without the change, but I just did another capture locally to verify and it still crashes. I'm uploading it now...

**Comment by zmike** [comment]
[trace](https://mega.nz/file/VQUCxbgR#22PddxpNA-GsQTYD3qexxVb-MQahbCS_8R2dLGGcn_w)

**Comment by jrfonseca** [comment]
Same problem:

```
...
4286026 @0 glMultiDrawElementsIndirect(mode = GL_TRIANGLES, type = GL_UNSIGNED_INT, indirect = 0x7fffd8037bf0, drawcount = 1, stride = 20)
spring: /home/jfonseca/projects/apitrace/retrace/retrace_swizzle.cpp:169: std::map<long long unsigned int, retrace::Region>::iterator retrace::lookupRegion(long long unsigned int): Assertion `contains(it, address)' failed.
```

`indirect` is still not being recognised as a blob, despite there has never been a single `glBindBuffer(GL_DRAW_INDIRECT_BUFFER)` call.

Either:
1. https://github.com/zmike/apitrace/commit/5e9428d62a464c68dd4f71ba1b621695c4fc6713 has a bug somewhere
2. the wrong `glxtrace.so` is not being used
3. `glGetIntegerv(GL_DRAW_INDIRECT_BUFFER, ...)` is giving bogus results

Some carefully added printfs to `glMultiDrawElementsIndirect`'s body should tell which is happenin.

**Comment by jrfonseca** [comment]
I think I found the problem.

I believe this should fix it:

```diff
diff --git a/specs/glapi.py b/specs/glapi.py
index 89cf67db..6732ca3b 100644
--- a/specs/glapi.py
+++ b/specs/glapi.py
@@ -778,8 +778,8 @@ glapi.addFunctions([
 
     # GL_VERSION_4_6
     GlFunction(Void, "glSpecializeShader", [(GLshader, "shader"), (GLstringConst, "pEntryPoint"), (GLuint, "numSpecializationConstants"), (Array(Const(GLuint), "numSpecializationConstants"), "pConstantIndex"), (Array(Const(GLuint), "numSpecializationConstants"), "pConstantValue")]),
-    GlFunction(Void, "glMultiDrawArraysIndirectCount", [(GLenum_mode, "mode"), (GLpointerConst, "indirect"), (GLintptr, "drawcount"), (GLsizei, "maxdrawcount"), (GLsizei, "stride")]),
-    GlFunction(Void, "glMultiDrawElementsIndirectCount", [(GLenum_mode, "mode"), (GLenum, "type"), (GLpointerConst, "indirect"), (GLintptr, "drawcount"), (GLsizei, "maxdrawcount"), (GLsizei, "stride")]),
+    GlFunction(Void, "glMultiDrawArraysIndirectCount", [(GLenum_mode, "mode"), (GLdrawArraysIndirectBuffer(), "indirect"), (GLintptr, "drawcount"), (GLsizei, "maxdrawcount"), (GLsizei, "stride")]),
+    GlFunction(Void, "glMultiDrawElementsIndirectCount", [(GLenum_mode, "mode"), (GLenum, "type"), (GLdrawElementsIndirectBuffer(), "indirect"), (GLintptr, "drawcount"), (GLsizei, "maxdrawcount"), (GLsizei, "stride")]),
 
     # GL_VERSION_ES_CM_1_0
     GlFunction(Void, "glClipPlanef", [(GLenum, "plane"), (Array(Const(GLfloat), 4), "equation")]),
@@ -1189,8 +1189,8 @@ glapi.addFunctions([
     GlFunction(Void, "glMultiDrawElementsBaseVertex", [(GLenum_mode, "mode"), (Array(Const(GLsizei), "drawcount"), "count"), (GLenum, "type"), (Array(Const(GLindexBuffer("count[{i}]", "type")), "drawcount"), "indices"), (GLsizei, "drawcount"), (Array(Const(GLint), "drawcount"), "basevertex")]),
 
     # GL_ARB_draw_indirect
-    GlFunction(Void, "glDrawArraysIndirect", [(GLenum_mode, "mode"), (GLdrawArraysIndirectBuffer())]),
-    GlFunction(Void, "glDrawElementsIndirect", [(GLenum_mode, "mode"), (GLenum, "type"), (GLdrawElementsIndirectBuffer())]),
+    GlFunction(Void, "glDrawArraysIndirect", [(GLenum_mode, "mode"), (GLpointerConst, "indirect")]),
+    GlFunction(Void, "glDrawElementsIndirect", [(GLenum_mode, "mode"), (GLenum, "type"), (GLpointerConst, "indirect")]),
 
     # GL_ARB_draw_instanced
     GlFunction(Void, "glDrawArraysInstancedARB", [(GLenum_mode, "mode"), (GLint, "first"), (GLsizei, "count"), (GLsizei, "instancecount")]),
diff --git a/specs/gltypes.py b/specs/gltypes.py
index 2dbd6722..75c020e8 100644
--- a/specs/gltypes.py
+++ b/specs/gltypes.py
@@ -319,7 +319,7 @@ def GLdrawArraysIndirectBuffer():
     # - offsets when element array buffer is bound
     # - or a blob otherwise.
     return Polymorphic('_draw_indirect_buffer_binding()', [
-            ('0', Blob(Const(GLvoid), 16)),
+            ('0', Blob(Const(GLvoid), 'drawcount*16')),
         ],
         IntPointer("const GLvoid *"), 
         contextLess=False,
@@ -330,7 +330,7 @@ def GLdrawElementsIndirectBuffer():
     # - offsets when element array buffer is bound
     # - or a blob otherwise.
     return Polymorphic('_draw_indirect_buffer_binding()', [
-            ('0', Blob(Const(GLvoid), 20)),
+            ('0', Blob(Const(GLvoid), 'drawcount*20')),
         ],
         IntPointer("const GLvoid *"), 
         contextLess=False,
```

**Comment by jrfonseca** [comment]
https://github.com/apitrace/apitrace/tree/issue-903

**Comment by zmike** [comment]
Tested your branch and captures still crash the same way on replay.

**Comment by jrfonseca** [comment]
Out of ideas then.  Can you confirm whether the crashing `glMultiDrawElementsIndirectCount` call has a blob or not?

**Comment by zmike** [comment]
Doesn't appear to be recognized as a blob, no.

**Comment by jrfonseca** [comment]
I wrote a test case (https://github.com/apitrace/apitrace-tests/commit/b0a8664b63eaa654234bd10e545b1f664b10984c) did a few more fixes (now catching all "gl*Draw*Indirect*" calls which wasn't the case), and confirmed I'm getting blobs, both with NVIDIA and Mesa:

```
$ apitrace trace -o drawarraysindirect.trace apps/gl/varray drawarraysindirect && apitrace dump --grep 'Indirect' drawarraysindirect.trace
[...]
7579 glDrawArraysIndirect(mode = GL_TRIANGLE_STRIP, indirect = blob(16))
```

Please try one more time.

**Comment by zmike** [comment]
It works!
